.TH KROMAN 1 "July 20, 2015" "kroman"

.SH NAME
kroman \- Korean Hangul to Roman Converter
.SH SYNOPSIS
.B kroman
[
.B \-v
.I Version
] [
.B \-h
.I Help
]

.SH DESCRIPTION
.B kroman
is a command line utility for converting Korean Hangul to Roman syllables.
Just given it input, and you get converted output.

.SH OPTIONS
.TP
.B \-h (\-\-help)
see usage
.TP
.B \-v (\-\-version)
see version

.SH BUGS
Please report bugs at: https://github.com/cheunghy/kroman/issues

.SH HOMEPAGE
https://github.com/cheunghy/kroman

.SH AUTHOR
This software and manual was written by Zhang Kai Yu <yeannylam@gmail.com>.
